[package]
name = "dem"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]

[[bin]]
doc = false
name = "dem_test"
path = "src/main.rs"

[dependencies]
# Used for decompressing string table packets compressed with Snappy
snap = "1.0.2"
