[package]
name = "dem"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]

[[bin]]
doc = false
name = "dem_test"
path = "src/main.rs"

[dependencies]
arrayref = "^0.3.2"
byteorder = "1.0.0"
snap = "0.2.3"