[package]
name = "bitstream"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]
edition = "2018"
description = "Abstractions for parsing data from streams of bits and bytes"
license = "GPL-3.0-or-later"
