[package]
name = "dumper"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]
edition = "2018"
description = "Dumps the content of Source Engine demo files to readable formats"

[dependencies]
bitstream = { path = "../bitstream" }
demo = { path = "../demo" }
